name: Zigbee Devices Manager
version: "0.3.1"
slug: zigbee_devices_manager
description: Geräte-Namen für Zigbee-Geräte zentral verwalten – mit Namensschema, Kürzeln und automatischem Hochzählen.
url: https://github.com/BuRnEd4AiM/Zigbee-Devices-Manager
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:zigbee
panel_title: Zigbee Namen
panel_admin: true
homeassistant_api: true
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
  - type: all_addon_configs
    read_only: false
options:
  z2m_base_topic: zigbee2mqtt
schema:
  z2m_base_topic: str
